/**
 * Taxonomía de la agenda municipal: título normalizado → género de la app.
 *
 * POR QUÉ EXISTE: el CSV publicado no trae las columnas de taxonomía
 * (`secondary_filters_*` vienen vacías en las 3514 filas, verificado
 * 2026-09-30), así que el normalizador solo ve el título y el 95 % del
 * catálogo quedaba con `genre = null` → invisible al filtrar.
 *
 * CÓMO SE HA CONSTRUIDO: cruzando el CSV contra el JSON de 173 MB (que sí
 * trae la clasificación real de cada evento) y guardando el subgénero por
 * TÍTULO NORMALIZADO, no por `register_id`: la fuente renumera los ids en
 * cada republicación, el título es estable.
 *
 * Solo se incluyen los títulos con subgénero INQUIVOCO (808 de 809; se
 * descartó 1 con dos subgéneros distintos). El runtime NO descarga el
 * JSON: la tabla va embebida y versionada aquí.
 *
 * Auditoría hecha sobre el resultado: los 340 títulos marcados `classic`
 * son en su mayoría música clásica real (Mahler, Mozart, Bach, Sonatas,
 * óperas), no un artefacto de la taxonomía. Aplicado sobre los 457 eventos
 * que hay hoy en la BD, cubre el 64 % (jazz 53 · pop 78 · classic 83 ·
 * rock 35 · world 33 · electronic 9) y deja el 36 % restante en `null`,
 * que es lo honesto: preferimos sin género a inventar uno.
 */
import { normalizeText } from '../ingest/dedupe.ts';
import type { AppGenre } from '../types.ts';
/**
 * `classical` es el 42 % de la tabla (340 títulos: Mahler, Mozart, Bach,
 * óperas). Estuvo en `null` hasta que la app añadió el género el 2026-09-30:
 * forzarlo a `pop` habría sido inventar.
 */
export const BCN_TITLE_GENRE: Readonly<Record<string, AppGenre>> = {
  // 808 entradas generadas de docs/TAXONOMIA-BCN.md
  '27 festival mil lenni': 'jazz',
  '31 festival internacional de m sica experimental lem 2026': 'electronic',
  '36 festival l hora del jazz memorial tete montoliu': 'jazz',
  '3r festival super 90 s': 'pop',
  '58 festival internacional de jazz de barcelona': 'jazz',
  'accademia nazionale di santa cecilia harding txaikovski i brahms': 'classical',
  'acte d inauguraci del curs 26 27 al conservatori municipal de m sica de barcelona': 'classical',
  'acte inaugural al museu de la m sica': 'classical',
  'activitat cercatapes musical': 'pop',
  'activitat piano al carrer': 'classical',
  'activitat vermut musical': 'pop',
  'actuaci de la banda municipal de barcelona': 'pop',
  'actuaci de la banda simf nica de les corts': 'pop',
  'actuaci del grup joan pelegr music band': 'pop',
  'actuaci musical': 'pop',
  'actuacions musicals': 'pop',
  'advent coral a l alcaldia de sants montju c': 'classical',
  'aldafarra 26 celebraci dels 19 anys del cau aldaia': 'pop',
  'aperitiu la rumba que tumba': 'pop',
  'aperitiu musical': 'pop',
  'audici de nadal a c rrec d escola de m sica de sant gervasi': 'classical',
  'audicions pedrera 3 8': 'pop',
  'berenar pels avis amb ballaruca': 'pop',
  'botifarrada popular actuaci del grup the dominics': 'pop',
  'cantada d havaneres': 'pop',
  'castanyada i xerinola': 'pop',
  'castaween beats': 'electronic',
  'cercaentitats': 'pop',
  'cicle cl ssica a la reial acad mia tardor 2026 hivern 2027': 'classical',
  'cicle de cobla a barcelona 2026': 'pop',
  'cicle de concerts bcn cl ssics temporada 2026 2027': 'classical',
  'cicle de concerts friday blues': 'jazz',
  'cicle de concerts saturday classics': 'classical',
  'cicle de m sica a casa bartomeu jard dels tarongers': 'classical',
  'cicle microconcerts al caixaf rum': 'classical',
  'cocodril club revival amb l albert malla': 'pop',
  'concert': 'jazz',
  'concert 30 aniversario omega': 'pop',
  'concert 31 fam': 'pop',
  'concert 500 noches homenatge a sabina': 'rock',
  'concert a b ensemble': 'classical',
  'concert a contra blues 20 aniversari': 'jazz',
  'concert a tempo de vals duo vesta': 'classical',
  'concert a una veu': 'pop',
  'concert abril': 'electronic',
  'concert aespa': 'pop',
  'concert afrobrasileira': 'jazz',
  'concert aires llatins': 'pop',
  'concert aix parla zarathustra de strauss': 'classical',
  'concert alba pujals sincretisme': 'jazz',
  'concert alba ventura': 'classical',
  'concert albert cirera tres tambors': 'jazz',
  'concert alberttinny': 'pop',
  'concert aleks syntek': 'pop',
  'concert alex fern ndez': 'pop',
  'concert alexandra dovgan': 'classical',
  'concert alg rad': 'pop',
  'concert all que roman amb andrea g mez oncina i laura de arenzana': 'classical',
  'concert amaia': 'pop',
  'concert amaral': 'pop',
  'concert amb la lonelys band': 'pop',
  'concert amb mallorkings i pica pica musical': 'pop',
  'concert amelie wienh fer': 'classical',
  'concert amelio trio': 'classical',
  'concert amitan': 'rock',
  'concert amon amarth': 'rock',
  'concert ana brenes': 'pop',
  'concert ana brenes mientras camino': 'pop',
  'concert anciients': 'rock',
  'concert andrea motis yamandu costa': 'jazz',
  'concert andsnes philharmonia orchestra salonen beethoven i bruckner': 'classical',
  'concert ang le': 'pop',
  'concert anggie obin quintet': 'jazz',
  'concert anila padr s folk': 'pop',
  'concert anja mitterm ller': 'classical',
  'concert anna amig': 'classical',
  'concert antamarta': 'pop',
  'concert antonio orozco': 'pop',
  'concert antonio serrano kaele jim nez': 'pop',
  'concert appassionata de beethoven amb anna fedorova': 'classical',
  'concert arlo parks': 'pop',
  'concert arnau brichs morphosis ensemble': 'electronic',
  'concert arquitectura sonora com es construeix la m sica a c rrec de la petita companyia l rica de bcn': 'classical',
  'concert arquitectures de l nima': 'classical',
  'concert arrels amb cor de noies de l orfe catal cor aurum': 'classical',
  'concert as canta jerez en navidad': 'pop',
  'concert ayden': 'pop',
  'concert bach amb marimba amb barbican quartet david moliner': 'classical',
  'concert bach beethoven i ravel amb yulianna avdeeva': 'classical',
  'concert bach haydn i mozart amb judith j uregui franz schubert filharmonia': 'classical',
  'concert bach i glass amb kebyart': 'classical',
  'concert bach i mozart amb quartet casals camerata casals': 'classical',
  'concert bach s nchez verd v squez victoria i falla amb alard colom arias octavio s nchez barrag n': 'classical',
  'concert band of horses': 'pop',
  'concert banda simf nica de les corts': 'pop',
  'concert barcelona jazz orquestra tot recordant satchmo homenatge a louis armstrong': 'jazz',
  'concert barry b': 'pop',
  'concert batiashvili royal concertgebouw orchestra m kel schumann sibelius i dvo k': 'classical',
  'concert bcuc': 'pop',
  'concert bebe': 'pop',
  'concert beca alicia de larrocha amb arielle beck': 'classical',
  'concert beethoven i mezquida amb l orquestra simf nica del vall s marco mezquida espasa': 'classical',
  'concert beethoven i schubert amb h l ne grimaud': 'classical',
  'concert beethoven integral de les sonates per violoncel i piano amb pau codina i marc heredia': 'classical',
  'concert beethoven ligeti i stockhausen amb pierre laurent aimard': 'classical',
  'concert beethoven sinfonia 5 i 6 amb jordi savall': 'classical',
  'concert bel n aguilera': 'pop',
  'concert bel n bandera carla motis quartet': 'jazz',
  'concert big band swing': 'jazz',
  'concert blood red shoes': 'rock',
  'concert bobby carcass s': 'jazz',
  'concert bonis serra i brahms amb trio naya garioud blanch': 'classical',
  'concert brahms amb perianes zimmermann queyras': 'classical',
  'concert brahms un r quiem alemany amb jordi savall': 'classical',
  'concert branford marsalis quartet dianne reeves celebrate john coltrane': 'jazz',
  'concert brentano string quartet': 'classical',
  'concert brou de nadal amb maria esteban tr o': 'jazz',
  'concert bruce liu': 'classical',
  'concert bryan adams': 'pop',
  'concert bryant myers': 'rock',
  'concert budapest festival orchestra fischer simfonia n m 9 de beethvoen': 'classical',
  'concert buhos': 'pop',
  'concert c est la vie a c rrec de modus operandi': 'classical',
  'concert cala vento': 'rock',
  'concert calitja': 'classical',
  'concert calme des nuits de saint sa ns amb cor jove de l orfe catal la ma trise de toulouse': 'classical',
  'concert camela': 'pop',
  'concert camil arcarazo': 'jazz',
  'concert can d amor i de guerra amb l orquestra simf nica del vall s franc s i cruz': 'classical',
  'concert can ons i estudis dos pilars de la m sica a c rrec de duo amoria': 'classical',
  'concert candor piano trio': 'classical',
  'concert cano': 'electronic',
  'concert cant ria cantada de carles santos': 'classical',
  'concert canta gran espardenya blanca al peu': 'classical',
  'concert cantada de nadales': 'classical',
  'concert capu on nederlands philharmonic viotti dvo k i txaikovski': 'classical',
  'concert carlos ares': 'pop',
  'concert carlos n ez': 'pop',
  'concert carlos sadness': 'pop',
  'concert carminho': 'pop',
  'concert carolina alabau i lia bastida': 'jazz',
  'concert carolina deslandes': 'pop',
  'concert carolina durante': 'pop',
  'concert carta blanca a charlotte bray': 'classical',
  'concert cecilia bartoli lang lang': 'classical',
  'concert celobert': 'pop',
  'concert centenari d oriol martorell amb coral sant jordi 80 aniversari': 'classical',
  'concert centenari garc a m rquez amb francesc orella i jos r pascual vilaplana': 'classical',
  'concert chiara oliver': 'pop',
  'concert chiquita movida': 'pop',
  'concert chris potter': 'jazz',
  'concert cimafunk': 'jazz',
  'concert cinc segles d emocions l arquitectura vista des de la m sica a c rrec de barcelona brass': 'classical',
  'concert cl ssic bcn': 'classical',
  'concert claire huangci': 'classical',
  'concert claire i gonzalo duo folk': 'pop',
  'concert classical new classical music': 'classical',
  'concert cloenda de temporada amb ludovic morlot i kirill gerstein': 'classical',
  'concert cobla sant jordi ciutat de barcelona sabata massana': 'classical',
  'concert colors band': 'rock',
  'concert con spirito classicisme poli dric': 'classical',
  'concert con spirito clementi i haydn l art del piano cl ssic': 'classical',
  'concert concert de nadal aromita': 'classical',
  'concert concert per a piano de chopin amb cristian macelaru i david khrikuli': 'classical',
  'concert concert pro pacem una celebraci de pau i esperan a amb jordi savall': 'classical',
  'concert concerts per a dos teclats d antoni soler amb dani espasa juan de la rubia': 'classical',
  'concert constel lacions peces errants ap crifs i el bach llegendari integral de l obra per a orgue de j s bach iv': 'classical',
  'concert cor folk': 'pop',
  'concert coral del cor de dones i cor mixt': 'classical',
  'concert coral i rondalla virrei amat': 'classical',
  'concert coral oronell': 'classical',
  'concert cosmos quartet': 'classical',
  'concert cosmos quartet arete quartet': 'classical',
  'concert costa stars': 'rock',
  'concert crazy rhythm cats': 'pop',
  'concert creaci musical contempor nia orquestra de cambra catalana': 'classical',
  'concert cris lopezz quartet': 'jazz',
  'concert crossinglines': 'classical',
  'concert cuarteto quiroga': 'classical',
  'concert curses': 'pop',
  'concert d havaneres': 'pop',
  'concert d havaneres a c rrec del grup crema catalana': 'pop',
  'concert d orgue': 'pop',
  'concert dani martin dins la gira 25 p t s a os': 'pop',
  'concert daniil trifonov': 'classical',
  'concert de cap d any amb peyu i arnau tordera': 'classical',
  'concert de celebraci del 40 aniversari de l orquestra de cambra catalana': 'classical',
  'concert de cloenda paisatges sonors en obert el teixit musical de la pastoral a c rrec de l orquestra simf nica tekhn': 'classical',
  'concert de cloenda rakhm ninov concert de piano': 'classical',
  'concert de festa major': 'pop',
  'concert de festa major amb son de la rambla': 'pop',
  'concert de jazz i sopar de carmanyola de dones de les corts': 'pop',
  'concert de la banda municipal de barcelona': 'pop',
  'concert de la josc': 'pop',
  'concert de los imposibles al live room del conservatori del liceu': 'pop',
  'concert de monteverdi a charles amb cor cererols': 'classical',
  'concert de nadal a c rrec de l alumnat de musicart sarri': 'classical',
  'concert de nadal amb alumnes de l escola de m sica joana pons': 'classical',
  'concert de nadal amb l alumnat de l escola de cant montserrat aparici': 'classical',
  'concert de nadal banda simf nica de les corts': 'classical',
  'concert de nadal big band swing': 'jazz',
  'concert de nadal de l orquestra de cambra de barcelona': 'classical',
  'concert de nadal de la coral del parc de la vall d hebron': 'classical',
  'concert de nadal del cors de can ponsic': 'classical',
  'concert de nadal m siques per la pau amb jos r pascual vilaplana': 'classical',
  'concert de nadal orquestra de cambra catalana': 'classical',
  'concert de nadal romeu i julieta amb adda simf nica alacant josep vicent': 'classical',
  'concert de profundis m sica de quaresma i passi integral de l obra per a orgue de j s bach vi': 'classical',
  'concert de sant esteve a c rrec dels cors de l orfe catal i cor de cambra del palau': 'classical',
  'concert de santa cec lia la 5a estaci quintet de cambra': 'classical',
  'concert de tardor 2026 coral collserola vallvidrera': 'classical',
  'concert de tardor passi per la cobla': 'classical',
  'concert de vocht bruch i strauss amb hadelich albrecht antwerp symphony orchestra': 'classical',
  'concert deacon blue': 'pop',
  'concert debussy c novas cornudella wenn koski i reich amb neuma': 'classical',
  'concert debussy glass i rameau amb v kingur lafsson': 'classical',
  'concert deep purple': 'rock',
  'concert del 50 aniversari del b stia de l oriol tramvia': 'rock',
  'concert del gran cantautor miquel del roig': 'pop',
  'concert del record al present': 'classical',
  'concert deler duo': 'jazz',
  'concert depresi n sonora': 'pop',
  'concert deutsche radio philarmonie pons wagner i strauss': 'classical',
  'concert diada de l antic cantaire amb xarxa coral': 'classical',
  'concert diada del soci del ce laiet': 'pop',
  'concert diada pau casals 2026 amb julia hagen lukas sternath': 'classical',
  'concert diana navarro': 'pop',
  'concert dido i enees de purcell amb cor jove de l orfe catal vespres d arnad pablo larraz': 'classical',
  'concert diego el cigala': 'pop',
  'concert divididos': 'rock',
  'concert dj marc castrelo': 'pop',
  'concert dollar selmouni': 'jazz',
  'concert dominguinho': 'pop',
  'concert duda beat': 'jazz',
  'concert duets de violins amb dmitri smirnov joel bardolet': 'classical',
  'concert duke ellington songbook': 'jazz',
  'concert duncan dhu mikel erentxun': 'pop',
  'concert duo din mic de rock n roll': 'pop',
  'concert duot 20 anys': 'jazz',
  'concert ed maverick': 'pop',
  'concert eddie henderson quartet': 'jazz',
  'concert edu cabello': 'jazz',
  'concert efectes secundaris i divina mol cula': 'rock',
  'concert el banquet celestial comuni i pres ncia integral de l obra per a orgue de j s bach ix': 'classical',
  'concert el barrio': 'pop',
  'concert el cant de la terra concert del 150 aniversari de la societat coral amics de la uni josep vila jover': 'classical',
  'concert el cicle infinit un passeig musical per la vida': 'classical',
  'concert el concert per a piano de brahms amb stefan dohr maxim lando': 'classical',
  'concert el concert per a piano de txaikovski amb yulianna avdeeva gabriel bebeselea franz schubert filharmonia': 'classical',
  'concert el dia sense oc s la llum de pasqua integral de l obra per a orgue de j s bach vii': 'classical',
  'concert el geni de liszt amb saskia giorgini': 'classical',
  'concert el mar de cerca a c rrec de ana laura garcia maria paz sotullo': 'classical',
  'concert el messies de h ndel amb emmanuelle ha m le concert d astr e': 'classical',
  'concert el messies de h ndel amb vespres d arnad cor de cambra de granollers puig': 'classical',
  'concert el messies de h ndel rias kammerchor akamus doyle': 'classical',
  'concert el pessebre de pau casals cor madrigal franz schubert filharmonia colomer': 'classical',
  'concert el piano com a vehicle d expressi art stica': 'classical',
  'concert el piano de mozart amb marta gardolinska i saskia giorgini': 'classical',
  'concert el requiem de mozart amb guillermo garc a calvo franz schubert filharmonia': 'classical',
  'concert el trencanous de txaikovski': 'classical',
  'concert el trencanous de txaikovski amb ludovic morlot james ehnes': 'classical',
  'concert el trencanous de txaikovski amb orquestra simf nica del vall s': 'classical',
  'concert el tri': 'rock',
  'concert elefantes': 'jazz',
  'concert elionor mart nez': 'classical',
  'concert els colors del quintet de vent viatge del cl ssic a la modernitat a c rrec de quintet apolo': 'classical',
  'concert els nostres cl ssics': 'classical',
  'concert els pets': 'rock',
  'concert elvis tribute artist elvis tribute band': 'rock',
  'concert elyella': 'electronic',
  'concert en carlus i els seus amics': 'pop',
  'concert ensemble pygmailion pichon missa en do menor de mozart': 'classical',
  'concert entorn a c rrec de kic barroc': 'jazz',
  'concert eros ramazzotti': 'pop',
  'concert escenes teatralitzades de tosca de giacomo puccini': 'classical',
  'concert esdeekid': 'pop',
  'concert estacions trio ether': 'classical',
  'concert eternity in an hour de whitacre amb cor de cambra del palau eric whitacre': 'classical',
  'concert ethan iverson bill mchenry': 'jazz',
  'concert ethan iverson liceu big band': 'jazz',
  'concert faust queyras schiff the constellation choir orchestra gardiner beethoven': 'classical',
  'concert festival de valsos i danses amb l orquestra simf nica del vall s puig': 'classical',
  'concert festival llum bcn amb josep planells schiaffino': 'classical',
  'concert fidelio de beethoven monteverdi choir orchestre r volucionaire et romantique heras casado': 'classical',
  'concert filharm nica jove de col mbia orozco estrada rakhm ninov i stravinsky': 'classical',
  'concert fito fitipaldis': 'pop',
  'concert fontaines d c': 'pop',
  'concert foresta': 'pop',
  'concert francisco escudero el perrete i rub n lavaniegos': 'pop',
  'concert franco fagioli gabetta consort': 'classical',
  'concert frente cumbiero indus julieta garay la filosa hija de la coca en barcelona': 'pop',
  'concert galvan real': 'pop',
  'concert ginebras': 'pop',
  'concert ginest': 'pop',
  'concert goat milk shots': 'jazz',
  'concert gondwana quique neira': 'electronic',
  'concert gonzalo hermida': 'pop',
  'concert gracie abrams': 'pop',
  'concert grecas': 'pop',
  'concert grigory sokolov': 'classical',
  'concert guille galv n': 'pop',
  'concert guillem gisbert': 'pop',
  'concert gustavo dudamel amb la filarm nica de nova york': 'classical',
  'concert hakuna': 'pop',
  'concert hans luchs quartet': 'jazz',
  'concert hard gz': 'pop',
  'concert havaneres a c rrec del grup els pescadors de l escala': 'pop',
  'concert hayd e milan s javier colina': 'jazz',
  'concert henge': 'electronic',
  'concert hermeto s mothership': 'jazz',
  'concert heroica de beethoven': 'classical',
  'concert hillbilly moon explosion': 'rock',
  'concert himnes de h ndel amb cor de cambra del palau vespres d arnad espasa': 'classical',
  'concert hombres g': 'pop',
  'concert homenatge a alb niz amb virginia mart nez': 'classical',
  'concert homenatge a gaspar cassad amb laura perib ez friends': 'classical',
  'concert homenatge a rosa sabater amb alba ventura': 'classical',
  'concert homenatge dire straits amb alchemy project': 'rock',
  'concert hong kong philharmonic orchestra peltokoski mozart i bruckner': 'classical',
  'concert humanity in war amb thomas quasthoff amatis trio': 'classical',
  'concert humet rautavaara vaughan williams respighi i pag s corella amb l orquestra simf nica juli carbonell de les terres de lleida pag s corella': 'classical',
  'concert i confer ncia con spirito clementi i la transici al romanticisme': 'classical',
  'concert ibrahim maalouf': 'jazz',
  'concert impressions rom ntiques piano a 4 mans': 'classical',
  'concert improv s': 'pop',
  'concert in the air to band phil collins experience': 'pop',
  'concert inauguraci de l exposici de la xarxa gran del districte': 'classical',
  'concert inaugural 12a temporada 2026 27': 'classical',
  'concert inaugural bach partites sonates i suites per a viol': 'classical',
  'concert inaugural del projecte j lia nogu s': 'pop',
  'concert inaugural rhapsody in blue': 'classical',
  'concert inici del cam laberints i obstinats integral de l obra per a orgue de j s bach i': 'classical',
  'concert integral de les sonates per a violoncel i piano de beethoven amb gautier capu on frank braley': 'classical',
  'concert integral de les suites per a violoncel de bach amb jean guihen queyras': 'classical',
  'concert integral de quartets de xostak vitx i amb quartet gerhard': 'classical',
  'concert integral de sonates per a piano de mozart i amb christian blackshaw': 'classical',
  'concert integral de sonates per a piano de mozart ii amb christian blackshaw': 'classical',
  'concert invisible limits': 'pop',
  'concert irene reig': 'jazz',
  'concert irina rimes': 'rock',
  'concert israel fern ndez': 'jazz',
  'concert iv n ferreiro': 'pop',
  'concert ivan herzog': 'jazz',
  'concert j lia cruz': 'pop',
  'concert jalezz': 'pop',
  'concert javi medina': 'rock',
  'concert javus quartett': 'classical',
  'concert jazz tast amb montbau lovers': 'jazz',
  'concert jazz tast friends': 'pop',
  'concert jazztast friends': 'jazz',
  'concert jesse joy': 'pop',
  'concert jmsn': 'jazz',
  'concert joan chamorro presenta pau garcia lola pe aranda i cl udia rostey': 'jazz',
  'concert joan maragall simf nic amb la participaci especial de josep carreras': 'classical',
  'concert joanjo bosk': 'rock',
  'concert joe bonamassa': 'jazz',
  'concert joe jackson': 'pop',
  'concert johan de meij els llibres oblidats amb jose mor i jaume santonja': 'classical',
  'concert john poll n': 'rock',
  'concert jorge drexler': 'pop',
  'concert jove capella reial de catalunya': 'classical',
  'concert jove orquestra simf nica de barcelona': 'classical',
  'concert jpfernandez': 'pop',
  'concert julia rodr guez': 'jazz',
  'concert jungle': 'rock',
  'concert kabeaush aunty rayzor mooki6 miriam tntc': 'pop',
  'concert kaleo': 'pop',
  'concert karol g': 'pop',
  'concert kase o': 'pop',
  'concert khatia buniatishvili': 'classical',
  'concert kid francescoli': 'electronic',
  'concert kiki morente i jos carbonell montoyita': 'pop',
  'concert kod ly h ry j nos suite amb francesc prat': 'classical',
  'concert kolochi baw': 'rock',
  'concert kris tena': 'jazz',
  'concert kurt rosenwinkel': 'jazz',
  'concert kyle alessandro': 'pop',
  'concert kyle eastwood': 'jazz',
  'concert l arann': 'jazz',
  'concert l arquitectura de les emocions del classicisme a l expressi rom ntica a c rrec de quartet aur': 'classical',
  'concert l atl ntida de falla amb kent nagano i ocne': 'classical',
  'concert l emperador': 'classical',
  'concert l heroica de beethoven amb clara jumi kang sunwook kim': 'classical',
  'concert l ltima gran festa de l any': 'pop',
  'concert l nima en vers': 'classical',
  'concert l ocell de foc de stravinsky amb sol gabetta': 'classical',
  'concert la banda espectacular amb jos mic i bj rn bus': 'classical',
  'concert la casa azul': 'pop',
  'concert la cinquena de beethoven amb staatskapelle dresden gatti': 'classical',
  'concert la cinquena de prok fiev amb ludovic morlot i imogen cooper': 'classical',
  'concert la cinquena de txaikovski': 'classical',
  'concert la dansa del sabre amb l orquestra simf nica del vall s i aki berm dez pasquina': 'classical',
  'concert la f miga': 'rock',
  'concert la guitarra que va veure cr ixer barcelona a c rrec de joan furi': 'classical',
  'concert la h ngara': 'pop',
  'concert la kermesse redonda': 'rock',
  'concert la nit de l ara homenatge a luciano pavarotti amb l orquestra simf nica del vall s': 'classical',
  'concert la nit de nadal de joan lamote de grignon amb orquestra simf nica del vall s pasquina': 'classical',
  'concert la novena de beethoven amb sociedad coral de bilbao i jos r pascual vilaplana': 'classical',
  'concert la novena de beethoven amb staatskapelle dresden orfe catal gatti': 'classical',
  'concert la novena de mahler amb vassili petrenko': 'classical',
  'concert la novena de mahler amb yamada orchestre national du capitole de toulouse': 'classical',
  'concert la oreja de van gogh': 'pop',
  'concert la primera de brahms amb ludovic morlot': 'classical',
  'concert la quarta de xostak vitx amb andris poga': 'classical',
  'concert la rom ntica de bruckner': 'classical',
  'concert la rosa als llavis amb diego mart n etxebarria i violeta alarc n': 'classical',
  'concert la segona de mahler amb ludovic morlot i l orfe catal': 'classical',
  'concert la setena de beethoven': 'classical',
  'concert la setena de beethoven amb ludovic morlot i jan lisiecki': 'classical',
  'concert la simfonia del nou m n amb nad ge rochat chlo van soeterst de': 'classical',
  'concert la valqu ria de wagner amb ludovic morlot i kathleen o mara': 'classical',
  'concert la vuitena de xostak vitx amb michael sanderling i alexei volodin': 'classical',
  'concert las luces azules de mauro meloni': 'rock',
  'concert las migas': 'pop',
  'concert latinta': 'pop',
  'concert laura marchal': 'pop',
  'concert laura milazzo sextet': 'jazz',
  'concert laura misch': 'electronic',
  'concert lecomte de br geot live': 'electronic',
  'concert leif ove andsnes': 'classical',
  'concert lela soto': 'pop',
  'concert leoni torres': 'pop',
  'concert leonkoro quartet': 'classical',
  'concert les bandes sonores son el futur de la m sica cl ssica': 'classical',
  'concert les quatre estacions de vivaldi amb maria florea franz schubert filharmonia': 'classical',
  'concert les quatre estacions de vivaldi amb vespres d arnad james espasa': 'classical',
  'concert les variacions goldberg de bach a c rrec de trio orfeu': 'classical',
  'concert lido pimienta': 'pop',
  'concert lied amb guillem batllori joaquim font': 'classical',
  'concert lied amb helena ressurrei ao mar compte': 'classical',
  'concert lied amb ian koziara bradley moore': 'classical',
  'concert lied amb katharina bierweiler jyri mishukov': 'classical',
  'concert live in carmel 2026': 'rock',
  'concert living els 90': 'classical',
  'concert llum naixent advent i nadal integral de l obra per a orgue de j s bach iii': 'classical',
  'concert lola stouthamer s almost a quintet': 'jazz',
  'concert london philharmonic gardner brahms i sibelius': 'classical',
  'concert los 40 music awards santander 2026': 'pop',
  'concert los aurora x catalunya flamenca': 'pop',
  'concert los enemigos': 'rock',
  'concert los fabulosos cadillacs': 'rock',
  'concert los sara fontan': 'jazz',
  'concert los yakis': 'pop',
  'concert lotti palestrina monteverdi allegri i scarlatti amb musica reservata de barcelona': 'classical',
  'concert lucia fumero': 'jazz',
  'concert luck ra': 'pop',
  'concert m rquez mendelssohn i beethoven amb quartet gerhard': 'classical',
  'concert m sica alchemica i lina tur bonet': 'classical',
  'concert m sica catalana del segle xxi': 'classical',
  'concert m sica contempor nia infreq ent per a clavic mbal': 'classical',
  'concert m sica espanyola': 'classical',
  'concert m sica experimental macromassa': 'electronic',
  'concert macy gray': 'pop',
  'concert maggie cullen': 'pop',
  'concert mal': 'pop',
  'concert malm 040': 'pop',
  'concert manllevat i transformat l art de la transcripci integral de l obra per a orgue de j s bach ii': 'classical',
  'concert manu estrach': 'pop',
  'concert manu guix': 'pop',
  'concert mar a jos llergo': 'pop',
  'concert mar a mar n': 'pop',
  'concert mar oceana': 'classical',
  'concert marat el primer palau descobrint joves talents': 'classical',
  'concert marco mezquida': 'jazz',
  'concert maria escarmiento': 'pop',
  'concert marina herlop': 'jazz',
  'concert marina y su melao': 'pop',
  'concert mark guiliana beat music': 'jazz',
  'concert marta garret un a un': 'jazz',
  'concert marta garrett': 'pop',
  'concert marta garrett presenta un a un': 'jazz',
  'concert marta robles i alicia grillo': 'pop',
  'concert martin s nchez y los corazones salvajes': 'rock',
  'concert mary halvorson canis major': 'jazz',
  'concert mayte mart n': 'pop',
  'concert medina azahara': 'rock',
  'concert melendi': 'pop',
  'concert memi sillah group': 'jazz',
  'concert menta poleo lavin dogteeth': 'pop',
  'concert mercury rev sandy bell': 'rock',
  'concert merino': 'electronic',
  'concert metrika': 'pop',
  'concert meute': 'electronic',
  'concert michael foster': 'pop',
  'concert michel camilo trio amb ricky rodr guez i antonio s nchez': 'jazz',
  'concert michelle david the true tones': 'jazz',
  'concert michelle gurevich': 'pop',
  'concert midas alonso': 'pop',
  'concert miguel zen n i luis perdomo': 'jazz',
  'concert mirades des dels andes': 'classical',
  'concert miranda': 'pop',
  'concert missa de la coronaci de mozart amb l orquestra simf nica del vall s cor madrigal puig': 'classical',
  'concert missa en si menor de bach amb vox luminis freiburger barockorchester meunier': 'classical',
  'concert missa solemnis de beethoven le concert des nations la capella reial de catalunya savall': 'classical',
  'concert modigliani quartet': 'classical',
  'concert mois s p sanchez falla imaginado': 'jazz',
  'concert mompou liszt bach i franck amb josep colom': 'classical',
  'concert mono': 'rock',
  'concert morat': 'pop',
  'concert morgan': 'pop',
  'concert morgenshtern': 'rock',
  'concert morph a c rrec de duo kalon': 'classical',
  'concert mozart beethoven i schumann amb cosmos quartet alba ventura': 'classical',
  'concert mozart i txaikovski amb kebyart la camerata': 'classical',
  'concert mujeres': 'pop',
  'concert nadal de m sica cl ssica trio nadales': 'classical',
  'concert nadal nyand': 'pop',
  'concert nadine sierra orquestra de l pera royal de versalles mozart i donizetti': 'classical',
  'concert naruhiko kawaguchi': 'classical',
  'concert nate smith': 'pop',
  'concert nervy band': 'rock',
  'concert ni a polaca': 'pop',
  'concert ni o josele': 'pop',
  'concert niall horan': 'rock',
  'concert noctes cor de cambra': 'classical',
  'concert nostre gra terrrae': 'classical',
  'concert oasis live 27': 'pop',
  'concert obk': 'pop',
  'concert obra vocal en llat d antoni soler amb la grande chapelle albert recasens': 'classical',
  'concert obres de whitacre amb orfe catal cors de l escola coral de l orfe catal eric whitacre': 'classical',
  'concert obres per a cor d albert guinovart amb guinovart cor femen scherzo esteve nabona': 'classical',
  'concert odissea i els colors del mar d iniesta amb cor de noies de l orfe catal eduard iniesta': 'classical',
  'concert okdw': 'pop',
  'concert olivia rodrigo': 'pop',
  'concert omar sosa marcelo woloski focus quartet': 'jazz',
  'concert on habita l aire a c rrec de duo samkara': 'classical',
  'concert oney1': 'pop',
  'concert operaci pera la missi dels infants amb cor infantil de l orfe catal gl ria coma': 'classical',
  'concert oques grasses': 'pop',
  'concert oratori de nadal amb carlos mena i cor jove de l orfe catal': 'classical',
  'concert oratori de nadal amb collegium vocale gent herreweghe': 'classical',
  'concert orfe barcelon s': 'classical',
  'concert orfe catal orquestra simf nica del gran teatre del liceu puig elies de mendelssohn': 'classical',
  'concert orpheus chamber orchestra amb branford marsalis': 'jazz',
  'concert orquestra reial concertgebouw amb klaus m kel': 'classical',
  'concert orquestra s nica': 'jazz',
  'concert orquestra simf nica de barcelona i nacional de catalunya brotons toldr lamote de grignon i brotons': 'classical',
  'concert os garotin': 'pop',
  'concert pac fica': 'rock',
  'concert paco pecado': 'pop',
  'concert palau vincles fest concert de fi de curs': 'classical',
  'concert part i messiaen amb trio fortuny cristina mateo': 'classical',
  'concert passenger': 'pop',
  'concert passi segons sant mateu de bach amb currentzis utopia orchestra choir': 'classical',
  'concert passi segons sant mateu de bach amb rattle z rcher sing akademie freiburger barockorchester': 'classical',
  'concert pastora': 'electronic',
  'concert patax': 'pop',
  'concert pau pau pau la lluita de pau casals 150 aniversari': 'classical',
  'concert pausa street jazz band': 'jazz',
  'concert pd nyema i pd pikas': 'pop',
  'concert per a viol de brahms amb anne sophie mutter m nchner philharmoniker shani': 'classical',
  'concert per a violoncel d elgar amb ferr ndez gonz lez monjas musikkollegium winterthur': 'classical',
  'concert perianes san diego symphony orchestra payare ortiz schumann bernstein i bart k': 'classical',
  'concert petar pej i': 'classical',
  'concert pete bas': 'pop',
  'concert piano a quatre mans amb elisabeth leonskaja i julius drake': 'classical',
  'concert piazzolla mar a de buenos aires amb mercedes gancedo gustavo de gennaro marcelo mercadante i jos r pascual vilaplana': 'classical',
  'concert pitbull': 'pop',
  'concert placebo': 'rock',
  'concert playgrxvnd': 'jazz',
  'concert please u2 u2 50th anniversary': 'rock',
  'concert poda': 'jazz',
  'concert polyphia': 'pop',
  'concert pop rock simf nic amb l orquestra simf nica del vall s rubio': 'pop',
  'concert pop rock simf nic amb orquestra simf nica del vall s rubio': 'pop',
  'concert poulenc terzian falla hahn i garc a lorca amb ana mar a valderrama david kadouch': 'classical',
  'concert pu o drag n': 'pop',
  'concert pur funk clarence bekker band': 'jazz',
  'concert quartet casals': 'classical',
  'concert quatre ltimes can ons de strauss amb david afkham i ruzan mantashyan': 'classical',
  'concert quevedo': 'pop',
  'concert quiet colors': 'jazz',
  'concert rajery ra l rodr guez': 'jazz',
  'concert ramon mirabet all stars jazz project': 'jazz',
  'concert raul clyde': 'pop',
  'concert raynald colom feat diego amador': 'pop',
  'concert razorlight': 'pop',
  'concert ren pape orquestra simf nica del vall s verdi i wagner': 'classical',
  'concert renaldo clara': 'pop',
  'concert requiem de mozart amb orquestra simf nica del vall s': 'classical',
  'concert respighi festes romanes': 'classical',
  'concert responsoria hebdomadae sanctae de vivancos amb latvian radio choir klava': 'classical',
  'concert resson ncies del romanticisme saxo i piano': 'classical',
  'concert rezo al agua': 'pop',
  'concert rhapsody en blue amb ala voronkova i guerrassim voronkov': 'classical',
  'concert rhapsody in blue': 'classical',
  'concert rimski k rsakov capriccio espagnol amb ausi s parejo i jos r pascual vilaplana': 'classical',
  'concert rock explosion amb mst bulevart': 'rock',
  'concert rockpelsxuklis the adams family syncronicity': 'classical',
  'concert rodrigo y gabriela': 'rock',
  'concert roger mas': 'pop',
  'concert romeu i julieta amb jaime mart n i frank peter zimmermann': 'classical',
  'concert ruel': 'pop',
  'concert rumbach amb leticia moreno edicson ruiz gonzalo grau': 'classical',
  'concert ruslana': 'pop',
  'concert ryan adams': 'pop',
  'concert s ber': 'rock',
  'concert sabrina g rdez': 'classical',
  'concert salmo': 'rock',
  'concert samara joy': 'jazz',
  'concert sananda maitreya': 'rock',
  'concert sanisidro': 'pop',
  'concert sant andreu dixie band': 'jazz',
  'concert sant andreu jazz band': 'jazz',
  'concert sant andreu jazz band all stars retrat d artista frank louis': 'jazz',
  'concert santiago auser n': 'rock',
  'concert sara aldana': 'jazz',
  'concert sara hebe': 'electronic',
  'concert sara lilu alesander pe a': 'jazz',
  'concert sara roy': 'pop',
  'concert sardines en llauna': 'pop',
  'concert sax tango homantge a piazzolla': 'pop',
  'concert schubert brahms rossini i guastavino amb 5 elements math u pint padull s oliv bronevetzky': 'classical',
  'concert segon concert de rakhm ninov amb josep caball dom nech i marc heredia': 'classical',
  'concert semyon bychkov amb l orquestra filharm nica txeca': 'classical',
  'concert sen cello duo': 'classical',
  'concert sergio contreras': 'pop',
  'concert sergio dalma': 'pop',
  'concert setena de bruckner': 'classical',
  'concert sextets': 'classical',
  'concert sfdk': 'pop',
  'concert sharp pins': 'pop',
  'concert sienna': 'pop',
  'concert sienna spiro': 'pop',
  'concert simf nic orquestra amics de la m sica': 'classical',
  'concert simfonia del nou m n amb stanislav kochanovsky matthias goerne': 'classical',
  'concert simfonia dom stica de strauss': 'classical',
  'concert simfonia heroica amb sebastian weigle': 'classical',
  'concert simfonia italiana amb ludovic morlot i luis cabrera': 'classical',
  'concert simfonies n m 1 4 i 5 staatskapelle de dresden gatti': 'classical',
  'concert simfonies n m 2 i 3 staatskapelle de dresden gatti': 'classical',
  'concert simfonies n m 6 i 7 staatskapelle de dresden gatti': 'classical',
  'concert simfonies n m 8 i 9 staatskapelle de dresden gatti': 'classical',
  'concert simple plan': 'rock',
  'concert sobrezero': 'pop',
  'concert sofia ribeiro': 'jazz',
  'concert solidari mare mundi un nou horitz per a l alzheimer i l envelliment': 'classical',
  'concert solidari the tutsies a favor de mans unides susp s': 'classical',
  'concert sonata de brahms amb agustin hadelich i seong jin cho': 'classical',
  'concert sonata de chopin amb david khrikuli': 'classical',
  'concert sonata kreutzer': 'classical',
  'concert sonata kreutzer de beethoven amb leonidas kavakos enrico pace': 'classical',
  'concert sonates de mozart amb yunchan lim': 'classical',
  'concert sonates per a clave d antoni soler amb diego ares': 'classical',
  'concert songs soundtracks silly simphony': 'classical',
  'concert sonido bestial el musical': 'pop',
  'concert squeeze': 'pop',
  'concert standards del jazz amb benjamin le n trio': 'jazz',
  'concert suffocation ingested undeath eternal': 'rock',
  'concert suite gran canyon amb salvador brotons': 'classical',
  'concert susan santos': 'rock',
  'concert svetlana': 'pop',
  'concert synthony': 'electronic',
  'concert szymanowski say kopatchinskaja i beethoven amb patricia kopatchinskaja fazil say': 'classical',
  'concert tabanka djaz': 'pop',
  'concert tango vs cl ssica l art de trobar se en la difer ncia': 'classical',
  'concert tarda de musicals amb ana san mart n daniel angl s i sergi cuenca': 'classical',
  'concert tarquim': 'pop',
  'concert tasha tracie king kami dj livea marcolan': 'pop',
  'concert te deum amb jordi savall': 'classical',
  'concert teenage fanclub': 'rock',
  'concert temps era temps': 'classical',
  'concert tercera de mahler': 'classical',
  'concert terraza wakenius boussaguet': 'jazz',
  'concert thana alexa friends': 'jazz',
  'concert the bird yellow': 'jazz',
  'concert the jazz room tribut a frank sinatra i louis armstrong': 'jazz',
  'concert the kolors': 'pop',
  'concert the last internationale': 'pop',
  'concert the notwist news from planet zombie': 'jazz',
  'concert the riven': 'rock',
  'concert the sacred veil de whitacre amb cor de cambra del palau eric whitacre': 'classical',
  'concert the sadies': 'pop',
  'concert the sheepdogs': 'pop',
  'concert the strokes': 'pop',
  'concert the warning': 'rock',
  'concert the women we are the music we feel': 'jazz',
  'concert the world of hans zimmer 2027': 'electronic',
  'concert this is michael by lenny jay s': 'pop',
  'concert tini': 'pop',
  'concert tornar a la pla a amb maria jaume': 'electronic',
  'concert tr ada': 'jazz',
  'concert tres barrios': 'jazz',
  'concert tribut a bon jovi amb big mouthers': 'rock',
  'concert tribut a david bowie amb blackstars': 'rock',
  'concert tribut a raffaella carr': 'pop',
  'concert tributo a h roes del silencio amb iberia sumergida': 'rock',
  'concert tristan i isolda wagner sense paraules': 'classical',
  'concert trueno': 'pop',
  'concert tu otra bonita': 'pop',
  'concert two lanes': 'electronic',
  'concert un a un de marta garret': 'jazz',
  'concert un americ a par s de gershwin amb orquestra orfeus de nova york marsalis': 'classical',
  'concert un quintet de canyes a par s': 'jazz',
  'concert un sorbito de champ n homenaje a los brincos': 'pop',
  'concert va de vals amb cor de cambra del palau xavier puig': 'classical',
  'concert valeria castro': 'pop',
  'concert vanessa paradis': 'pop',
  'concert vent i foc l esperit i pentecosta integral de l obra per a orgue de j s bach viii': 'classical',
  'concert vents del nord resson ncies de buxtehude i b hm integral de l obra per a orgue de j s bach v': 'classical',
  'concert verde prato': 'jazz',
  'concert vermut solidari rock pels xuklis': 'classical',
  'concert vertixe sonora': 'classical',
  'concert vetusta morla': 'rock',
  'concert veus de la meva terra a c rrec de trio voces': 'classical',
  'concert vicente amigo': 'pop',
  'concert vicente mar n trio': 'jazz',
  'concert vieux farka tour': 'jazz',
  'concert vijay iyer': 'jazz',
  'concert villa lobos coll bach turina barrios mangor i alb niz amb pablo sainz villegas': 'classical',
  'concert visiones en rojo': 'rock',
  'concert viva suecia': 'pop',
  'concert vr f gazella rey don perro': 'pop',
  'concert wagner strauss amb pietari inkinen i saskia giorgini': 'classical',
  'concert walls': 'pop',
  'concert wiener s ngerknaben nens cantaires de viena': 'classical',
  'concert winterreise de schubert amb mark padmore paul lewis': 'classical',
  'concert xavi castillo 3 4': 'jazz',
  'concert xoel l pez': 'pop',
  'concert yard act': 'pop',
  'concert yerai cort s': 'pop',
  'concert yo bailo': 'pop',
  'concert yuja wang': 'classical',
  'concert zaratustra de strauss amb christian blex i mariona camats': 'classical',
  'concert zenet': 'pop',
  'concert zucchero': 'jazz',
  'concerts': 'pop',
  'concerts de damoridemort i xenia': 'pop',
  'concerts de ensemble jaume padr s i vertixe sonora': 'classical',
  'concerts i audicions del carill del palau de la generalitat': 'classical',
  'concerts setembre 2026 al harlem jazz club': 'jazz',
  'confer ncia del caprici espanyol a la glosa de l emigrant': 'classical',
  'confer ncia improv s a debat com es compon un concert': 'pop',
  'confer ncia m sica cl ssica beatles vs rolling stones respostes al dilema': 'electronic',
  'confer ncia m sica cl ssica maria callas vs montserrat caball diferents veus diferents vides': 'classical',
  'confer ncia oratori de nadal de joan lamote de grignon': 'classical',
  'corredrag': 'pop',
  'cremat de rom coca i presa de xocolata': 'pop',
  'diada castellera de festa major': 'pop',
  'escape room fake news': 'pop',
  'espectacle concert participatiu amb orfe catal cor de noies de l orfe catal puig': 'classical',
  'espectacle concert per la pau amb banda municipal de barcelona pascual vilaplana': 'classical',
  'espectacle despu s del diluvio electr nico de jordi latorre': 'pop',
  'espectacle firmamento amb esperanza garrido': 'pop',
  'espectacle inercia amb lorena oliva': 'pop',
  'espectacle pirot cnic terrestre est tic de cloenda de festa major foc fred': 'pop',
  'espectacle tributs yesterdays': 'pop',
  'festa a can ros s': 'pop',
  'festa de la cortsenca vol iv': 'pop',
  'festa de la diversitat': 'pop',
  'festa de la tapa musical al mercat de lesseps': 'pop',
  'festa de nadal amb xocolatada solid ria': 'pop',
  'festa del soci': 'pop',
  'festa dels 20 anys del tresc mazoni amics': 'pop',
  'festa intercultural': 'pop',
  'festa major al jard del clot d en salvi': 'pop',
  'festes patronals de la casa de cantabria de barcelona': 'pop',
  'festival cru lla bcn': 'pop',
  'festival ecoss 2026 festival divers i singular tecno eco transfeminista': 'electronic',
  'festival feroe 26 amb st paul the broken bones beth orton i tiwayo': 'pop',
  'festival guitar bcn 2026': 'pop',
  'festival jazz tast 2026': 'pop',
  'festival samfaina': 'pop',
  'gran concert de la banda municipal de barcelona': 'pop',
  'havaneres': 'pop',
  'havaneres amb el grup montju c': 'pop',
  'jazz tast i bingo musical a la pla a pastrana': 'jazz',
  'ludoteca entre jocs i passejades cantem': 'pop',
  'm sica al carrer amb discj queis': 'pop',
  'm sica en viu': 'pop',
  'matinal de festa major': 'pop',
  'mira festival 2026': 'electronic',
  'missa solemne en honor a sant jeroni patr de montbau': 'classical',
  'nit de concerts': 'pop',
  'nit de festa major de les corts sud': 'pop',
  'nit de m sica amb campikipugui i sucre mor': 'pop',
  'nit de m sica amb reines del mambo i dj sendo': 'pop',
  'nit de pd s pd flamisell pd ringidingi i pd ignacid': 'pop',
  'nit jove': 'pop',
  'passejada feminista i actuaci musical': 'pop',
  'posid nia green festival': 'pop',
  'preg de festa major': 'pop',
  'recital de guitarra a c rrec de v ctor franco': 'pop',
  'recital sabine devieilhe': 'classical',
  'salsaloneta': 'pop',
  'sessi din mica concert de nadal': 'classical',
  'sortida cultural anem a l auditori atl ntida de falla': 'classical',
  'sortida cultural anem a l auditori la setena de beethoven': 'classical',
  'sortida cultural anem a l auditori romeu i julieta': 'classical',
  'suite festival 2025 2026': 'pop',
  'tarda de nous talents': 'pop',
  'tardeig dels 80 90': 'pop',
  'tardeo musical': 'pop',
  'temporada gran teatre del liceu 2025 2026': 'classical',
  'trobada de corals de festa major': 'classical',
  'trobada de corals de tardor': 'classical',
  'trobada jam de blues cal bria 66': 'jazz',
  'txell las heras quintet': 'pop',
  'vespreig i nit de concerts': 'pop',
  'vespreig musical amb pla desendre a': 'pop',
  'viii cantada de nadales a la barceloneta': 'classical',
  'viu montju c 2026': 'pop',
  'xerrada escoltar amb els ulls a c rrec d anna bullich esta n': 'classical',
  'xerrada m s que muses': 'classical',
  'xerrada musical el pau casals m s desconegut 150 anys del seu naixement': 'classical',
  'xerrada musical les dones en les peres de puccini': 'classical',
  'xxxiv festival internacional de carill de barcelona': 'classical',

// resumen:
// {"classic": 340, "pop": 206, "world": 78, "electronic": 23, "jazz": 104, "rock": 57}
};

/**
 * Último recurso: deducir del título cuando no está en la tabla.
 * Las formas van acentuadas y sin acentuar ("electrónica" / "electronic"), que
 * es como las escribe la fuente.
 */
const TITLE_HINTS: ReadonlyArray<[RegExp, AppGenre]> = [
  [/\bjazz\b|\bblues\b|\bsoul\b|\bfunk\b/i, 'jazz'],
  [/\brock\b/i, 'rock'],
  [/\bpop\b/i, 'pop'],
  // `elec[a-z]*nic[a-z]*` a propósito: `\w` no cubre la `ó` de
  // "electrónica" y el patrón nunca casaba con la forma acentuada.
  [/elec[a-záéíóúàèòâêîôûäëïöüñ]*nic[a-záéíóúàèòâêîôûäëïöüñ]*|tecno|edm|techno/i, 'electronic'],
  [/flamen[co]|folk|world|salsa|tango/i, 'pop'],
];

/**
 * Género de la agenda municipal para un título, o `null` si no se sabe.
 * Se llama DESPUÉS de `mapGenre`: si el propio título ya delata el género
 * (y así lo hace la fuente), manda esa señal.
 */
export function genreFromTitle(title: string): AppGenre | null {
  const key = normalizeText(title);
  const fromTable = BCN_TITLE_GENRE[key];
  if (fromTable) return fromTable;
  for (const [pattern, genre] of TITLE_HINTS) {
    if (pattern.test(title)) return genre;
  }
  return null;
}
